"""
👻 PhantomRecon — Report Generator

Generates professional reports in Markdown, JSON, and HTML formats.
"""
import json
import datetime
from pathlib import Path


def generate_report(domain: str, results: dict, output_path: str,
                    fmt: str = "md", console=None) -> str:
    """Generate a scan report."""
    if fmt == "json":
        return _generate_json(domain, results, output_path, console)
    elif fmt == "html":
        return _generate_html(domain, results, output_path, console)
    else:
        return _generate_markdown(domain, results, output_path, console)


def _generate_markdown(domain: str, results: dict, output_path: str, console=None) -> str:
    """Generate Markdown report."""
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        f"# 👻 PhantomRecon — Scan Report",
        f"",
        f"**Target:** `{domain}`",
        f"**Date:** {now}",
        f"**Tool:** PhantomRecon v1.0.0",
        f"",
        f"---",
        f"",
    ]

    # Subdomains
    sub = results.get("subdomain", {})
    if sub and "error" not in sub:
        lines.append(f"## 🔍 Subdomains ({sub.get('total_count', 0)} found)")
        lines.append("")
        lines.append("| Subdomain | IP | Status | Source |")
        lines.append("|-----------|-----|--------|--------|")
        for s in sub.get("subdomains", [])[:50]:
            lines.append(f"| {s.get('subdomain','')} | {s.get('ip','')} | {s.get('status','')} | {s.get('source','')} |")
        lines.append("")

    # DNS
    dns = results.get("dns", {})
    if dns and "error" not in dns:
        lines.append(f"## 📡 DNS Records ({dns.get('total_records', 0)} records)")
        lines.append("")
        for rtype, records in dns.get("records", {}).items():
            lines.append(f"### {rtype} Records")
            for r in records:
                lines.append(f"- `{r.get('value', '')}` (TTL: {r.get('ttl', '')})")
            lines.append("")

    # WHOIS
    whois = results.get("whois", {})
    if whois and "error" not in whois:
        lines.append("## 📋 WHOIS Information")
        lines.append("")
        for key, val in whois.items():
            if val and key != "available":
                lines.append(f"- **{key.replace('_', ' ').title()}:** {val}")
        lines.append("")

    # Ports
    ports = results.get("ports", {})
    if ports and "error" not in ports:
        lines.append(f"## 🔌 Open Ports ({ports.get('open_count', 0)} open)")
        lines.append("")
        lines.append("| Port | Service | Banner |")
        lines.append("|------|---------|--------|")
        for p in ports.get("open_ports", []):
            lines.append(f"| {p['port']} | {p['service']} | {p.get('banner', '')[:60]} |")
        lines.append("")

    # Headers
    hdrs = results.get("headers", {})
    if hdrs and "error" not in hdrs:
        lines.append(f"## 🛡️ Security Headers (Grade: {hdrs.get('grade', 'N/A')})")
        lines.append("")
        primary = hdrs.get("results", {}).get("https", hdrs.get("results", {}).get("http", {}))
        for h in primary.get("headers", []):
            status = "✅" if h["present"] else "❌"
            lines.append(f"- {status} **{h['header']}** — {h['description']}")
        lines.append("")

    # SSL
    ssl_r = results.get("ssl", {})
    if ssl_r and "error" not in ssl_r:
        lines.append(f"## 🔒 SSL/TLS Certificate")
        lines.append("")
        lines.append(f"- **Valid:** {'Yes' if ssl_r.get('valid') else 'No'}")
        lines.append(f"- **Days Remaining:** {ssl_r.get('days_remaining', 'N/A')}")
        lines.append(f"- **Issuer:** {ssl_r.get('issuer', {}).get('organizationName', 'N/A')}")
        lines.append(f"- **SANs:** {ssl_r.get('san_count', 0)}")
        lines.append("")

    # Tech
    tech = results.get("tech", {})
    if tech and "error" not in tech:
        lines.append(f"## 🖥️ Technologies ({tech.get('total_detected', 0)} detected)")
        lines.append("")
        for cat, techs in tech.get("categories", {}).items():
            lines.append(f"- **{cat}:** {', '.join(techs)}")
        lines.append("")

    # AI Analysis
    ai = results.get("ai_analysis", "")
    if ai:
        lines.append("## 🤖 AI Analysis")
        lines.append("")
        lines.append(ai)
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Generated by [PhantomRecon](https://github.com/yourusername/phantomrecon) — AI-Powered Recon*")

    content = "\n".join(lines)
    Path(output_path).write_text(content, encoding="utf-8")

    if console:
        console.print(f"  📄 [bold green]Report saved:[/bold green] {output_path}")

    return output_path


def _generate_json(domain: str, results: dict, output_path: str, console=None) -> str:
    """Generate JSON report."""
    report = {
        "tool": "PhantomRecon v1.0.0",
        "target": domain,
        "timestamp": datetime.datetime.now().isoformat(),
        "results": results,
    }
    Path(output_path).write_text(json.dumps(report, indent=2, default=str), encoding="utf-8")

    if console:
        console.print(f"  📄 [bold green]Report saved:[/bold green] {output_path}")

    return output_path


def _generate_html(domain: str, results: dict, output_path: str, console=None) -> str:
    """Generate HTML report (wraps markdown)."""
    # Simple: generate markdown then wrap in styled HTML
    md_content = []
    md_content.append(f"<h1>👻 PhantomRecon Report — {domain}</h1>")
    md_content.append(f"<p><strong>Date:</strong> {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>")
    md_content.append(f"<pre>{json.dumps(results, indent=2, default=str)}</pre>")

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>PhantomRecon Report — {domain}</title>
<style>
body {{ font-family: 'Segoe UI', sans-serif; background: #0d1117; color: #c9d1d9; max-width: 900px; margin: 0 auto; padding: 40px; }}
h1 {{ color: #58a6ff; }} pre {{ background: #161b22; padding: 20px; border-radius: 8px; overflow-x: auto; font-size: 13px; }}
</style>
</head>
<body>{"".join(md_content)}</body>
</html>"""

    Path(output_path).write_text(html, encoding="utf-8")
    if console:
        console.print(f"  📄 [bold green]Report saved:[/bold green] {output_path}")
    return output_path
